### ISSUE TITLE
Very interesting project. Altcoin support?

### ISSUE THREAD

**Issue by eabz** [bitprim/bitprim-insight#151]
Hello. 
Is there any guidelines to integrate support for another cryptocurreny?
I actually hate the current bitpay-insight API and I use like 8 for a multi-currency wallet.

**Comment by garceri** [comment]
@cronos-polis what altcoins would you like to see supported the most ?

**Comment by cronos-polis** [comment]
I currently work with.
Polis: https://polispay.org/
GoByte: http://gobyte.network/
ColossusXT: https://colossusxt.io/
Monoeci: http://monoeci.io/
Dash: https://www.dash.org/
Also: BTC, BCH, LTC and ETH.
Actually, I think everyone will love an Insight-like API for ETH (I have integrated it with pseudo-utxos)

Just point me in the right direction and I'll start to integrate them.
