### ISSUE TITLE
Can the API and node on different hosts?

### ISSUE THREAD

**Issue by tyler-smith** [bitprim/bitprim-insight#208]
Is it possible to run a bitprim Bitcoin Cash node on one host and the bitprim API on another host, and have the API talk to the BCH node over RPC? The goal is to be able to scale the number of API instances up while all talking to a single BCH node.

I can't find any documentation or configuration options that look like they do this.

**Comment by dario-ramos** [comment]
Hi Tyler, what we do to scale this way is to configure one node as a "full node", and the rest as "forwarders". Check appsettings.json and you'll find keys to configure your API to work in forwarder mode, such as ForwarderUrl (set this to your full node's url), IIRC.

**Comment by tyler-smith** [comment]
Okay great, that looks like exactly what I need. Thanks.
