### ISSUE TITLE
Question: How to use insight api for bitcoin ABC

### ISSUE THREAD

**Issue by KursLabIgor** [bitprim/bitprim-insight#216]
Guys, please help me understand is it possible install insight api for bitcoin abc? 
i have run bitcoin abc node, how i can spin up it to this node?

**Comment by dario-ramos** [comment]
Hi Kurs! I'm sorry, but the bitprim-insight API is only compatible with the bitprim node (see bitprim-node project), not ABC.

**Comment by dario-ramos** [comment]
We can help you set up a bitprim node, including a database snapshot to skip syncing from scratch.

**Comment by KursLabIgor** [comment]
@dario-ramos  thanks for your quick answer. ok do we have some workaround. maybe some how install bitcoin or bitcoin cash with insight api, and then some how bitcoin cash points to bitcoinabc ?

**Comment by dario-ramos** [comment]
That wouldn't work because the interfaces are incompatible
