### ISSUE TITLE
Unable to build bitprim-insight latest release

### ISSUE THREAD

**Issue by KursLabIgor** [bitprim/bitprim-insight#227]
I have Linux Ubuntu 16.04. 
Before I run node version 0.16. Now i decided upgrade to latest version release since  were fixed defects for DB. 
**Note that i run node via bitprim-insight.** 
> I've made following steps: 
> 1.conan remove '*' -f
> 2. git pull  (for update sources)
> 3. dotnet build /p:BTC=true -c Release -v normal

Result of build: 
`"/root/bitprim-insight/bitprim.insight.sln" (Build target) (1:2) ->
 "/root/bitprim-insight/bitprim.insight/bitprim.insight.csproj" (default target) (2:7) ->
 (GetBitprimNodeCint target) -> 
 bitprim-database/0.18.0@bitprim/staging : error : Package '14d6bf9be066fb5fec0200c9442de2139bb2b3fb' build failed [/root/bitprim-insight/bitprim.insight/bitprim.insight.csproj]
EXEC : error : bitprim-database/0.18.0@bitprim/staging: Error in build() method, line 227 [/root/bitprim-insight/bitprim.insight/bitprim.insight.csproj]
/root/.nuget/packages/bitprim-btc/0.10.0/build/Common.targets(19,5): error MSB3073: The command "conan install . --install-folder=. -r bitprim" exited with code 1. [/root/bitprim-insight/bitprim.insight/bitprim.insight.csproj]`

    0 Warning(s)
    3 Error(s)
Full build Log attached: 
[build.log](https://github.com/bitprim/bitprim-insight/files/2831782/build.log)

**Comment by dario-ramos** [comment]
In line 194 of build.log:

`sh: 1: cmake: not found`

Cmake is not installed in your system, or it's not in PATH variable. It's a requirement.

**Comment by KursLabIgor** [comment]
yep. fixed
