### ISSUE TITLE
Unable to build BCH node for version 0.19.0

### ISSUE THREAD

**Issue by KursLabIgor** [bitprim/bitprim-insight#231]
Trying to update BCH testnet node from 0.18.0 to 0.19.0
My steps: 
1. conan remove '*' -f
2. dotnet build bitprim.insight.sln /p:BCH=true -c Release -v normal
3. dotnet publish bitprim.insight.sln /p:BCH=true -c Release -v normal -o published --framework=netcoreapp2.0

In result it is download and build 0.18.0 version. 
conan search retrun following result: 
```conan search
Existing package recipes:

bitprim-blockchain/0.18.0@bitprim/staging
bitprim-consensus/0.18.0@bitprim/staging
bitprim-core/0.18.0@bitprim/staging
bitprim-database/0.18.0@bitprim/staging
bitprim-network/0.18.0@bitprim/staging
bitprim-node/0.18.0@bitprim/staging
bitprim-node-cint/0.18.0@bitprim/stable
bitprim-node-cint/0.18.0@bitprim/staging
boost/1.66.0@bitprim/stable
gmp/6.1.2@bitprim/stable
icu/60.2@bitprim/stable
lmdb/0.9.22@bitprim/stable
secp256k1/0.11.0@bitprim/staging
```

**Comment by KursLabIgor** [comment]
trying fix it
https://github.com/bitprim/bitprim-insight/pull/232

**Comment by usatie** [comment]
Thanks.
I too want this to be fixed.

**Comment by dario-ramos** [comment]
Just approved Igor's PR, please pull and check if it is fixed

**Comment by KursLabIgor** [comment]
no fixed. as i mentioned in PR need to update nuget repository
`"/root/bitprim-insight/bitprim.insight.sln" (Restore target) (1) ->
       (Restore target) -> 
         /root/bitprim-insight/bitprim.insight/bitprim.insight.csproj : error NU1102: Unable to find package bitprim-bch with version (>= 0.10.1) [/root/bitprim-insight/bitprim.insight.sln]
       /root/bitprim-insight/bitprim.insight/bitprim.insight.csproj : error NU1102:   - Found 93 version(s) in nuget.org [ Nearest version: 0.10.0 ] [/root/bitprim-insight/bitprim.insight.sln]
         /root/bitprim-insight/bitprim.insight.tests/bitprim.insight.tests.csproj : error NU1102: Unable to find package bitprim-bch with version (>= 0.10.1) [/root/bitprim-insight/bitprim.insight.sln]
       /root/bitprim-insight/bitprim.insight.tests/bitprim.insight.tests.csproj : error NU1102:   - Found 93 version(s) in nuget.org [ Nearest version: 0.10.0 ] [/root/bitprim-insight/bitprim.insight.sln]
`

**Comment by amanoooooooooooooooo** [comment]
Could someone help me
I started a 0.19.0 bch node
```
conan remote add bitprim https://api.bintray.com/conan/bitprim/bitprim
conan install bitprim-node-exe/0.19.0@bitprim/stable 
./bn -i
./bn
```
then run  insight 
```
dotnet bin/Release/netcoreapp2.0/bitprim.insight.dll --server.port=3000 --server.address=0.0.0.0 --InitializeNode=false --ForwardUrl=http://localhost:8333 --ApiPrefix=api
```
then test
```
curl localhost:3000/api/sync
```
sadly , is return nothing, 

if i run insight with InitializeNode=true, rest will work ,but can not use 0.19.0 node,
Please help me

**Comment by KursLabIgor** [comment]
@amanoooooooooooooooo 
What for you are using --ForwardUrl=http://localhost:8333 this param? 
If you are not going to use forward request do not specify this param and --InitializeNode=true.
any way read carefully docs.

**Comment by KursLabIgor** [comment]
fixed. NOw able to build and start
