### ISSUE TITLE
When will this project release?

### ISSUE THREAD

**Issue by eshangui** [bitprim/bitprim-insight#70]
I am looking forward for a solution which supports insight-api on bitcoin cash, this seems to be the right thing, when will it release and show more documents? Thank you!

**Comment by garceri** [comment]
@eshangui , thanks for your interest in this project, we expect to release the first version this week, for a peek on how this works you can look at https://blockdozer.com which is currently using this code.
BTW: We are interested in seeing how this code will be used, what are your plans ?

**Comment by eshangui** [comment]
@garceri , thank you for your information, we are developing a hardware wallet for the common seen cryptocurrencies, so we need to run our own Bitcoin Cash full node with insight-api/insight-ui support, till now I've tried several solutions, but they all went wrong after the May 15th fork, your project seems to be the most reliable and easiest solution. Waiting for your good news.

**Comment by garceri** [comment]
We run blockdozer.com, the leading BCH explorer, instead of running your
own node, would you consider connecting the the blockdozer
(insight-compatible) API ?

**Comment by garceri** [comment]
[](url)

**Comment by garceri** [comment]
@eshangui , We run [blockdozer.com](url), the leading BCH explorer, instead of running your
own node, would you consider connecting the the our (insight-compatible) API, we can provide support for BCH/BTC and eventually LTC. [Exodus.io](url) already uses these services.

**Comment by eshangui** [comment]
@garceri thanks for your advice, we are using blockdozer for test already, but literally there will be two problems with it: 1. the latency now we access [blockdozer.com](url) is about 400ms, our own server will be only 40ms below. 2. we are located in China, the government's net control policy might have many uncertainties, so the website may be banned someday, so a domestic server will be much better.

**Comment by garceri** [comment]
@eshangui we will be more than glad to help you setup a bitprim-insight instance for you,  i gather you are interested in the api and not the explorer user interface, am i right?
Please send me an email to my github registered email so we continue the discussion privately.

**Comment by garceri** [comment]
@eshangui Please checkout our latest release 1.1.0 (along with the documentation) .  I'm closing the issues.
