### ISSUE TITLE
non-zero indexed outputs in mempool transactions

### ISSUE THREAD

**Issue by alwaysAn0n** [bitprim/bitprim-insight#95]
Bitcoin.com's insight node rejects transaction I build using UTXO data returned by the Blockdozer API but only if one of my inputs is unconfirmed.  After discovering this, I looked at the utxo data returned by an array of public facing nodes.  My results are here https://gist.github.com/alwaysAn0n/0d459b8ea22dadd7ee26c8e35a145e93 .

For a given output on an unconfirmed transaction, Blockdozer is showing the index as 1 greater than what is shown by the other explorers with the lowest value being 1 rather than zero.  In other words if a mempool transaction has two outputs, Blockdozer shows their indexes as 1 and 2 while the other explorers show them as 0 and 1.

Once the transaction is confirmed, Blockdozer shows the correct index.  Only after confirmation though.

I'm not certain this is the right place for this issue and I'm not even certain this is a bug.  Either way, I would love to understand why it's different.  Thanks!

**Comment by garceri** [comment]
Thanks for reporting this we are in the middle of a release for blockdozer.com, we will let you know once the issues have been fixes so you can verify

**Comment by renzobarrionuevo** [comment]
Hello alwaysAn0n 
We have made a new release of our API in which we have solved the problem that plated us.
Thank you very much for your cooperation.
