### ISSUE TITLE
Wrong data type returned for "satoshis" and "amounts" on unconfirmed outputs. 

### ISSUE THREAD

**Issue by alwaysAn0n** [bitprim/bitprim-insight#96]
While diagnosing #95 , I ran across this issue as well.  "amount" and "satoshis" field for outputs on mempool transactions come back as strings rather than numbers.  Once the transactions are confirmed, the problem goes away.  Below is an example.  I hit the `https://blockdozer.com/api/addrs/:cashAddress/utxo/` endpoint directly from the Chromium URL bar.

```[{"address":"1MJ2ZmRKigtB7B9K2q6pBaPpiwRppP794h","txid":"35b55dd8a72a79d8502cca524d24b56ec4d065e9ca7f7d540c84d6e9a53c9f6f","vout":1,"amount":4.521E-05,"satoshis":"4521","height":-1,"confirmations":0}]```

Note, in the example above, "amount" isn't a string but I've observed "amount" being returned as a string for larger values so I think that field is also a problem.

**Comment by bitprim-phabricator** [comment]
Can you try to reproduce this with [This](https://github.com/bitprim/bitprim-insight/tree/release/1.0.0) release ?

**Comment by alwaysAn0n** [comment]
@bitprim-phabricator Just saw this.  The link you provided yields a 404 error.  Either way though, I don't currently have a hosted node to test a release on.  I'm happy to test it if you're able to host it and provide me the API's base url.

**Comment by dario-ramos** [comment]
Try the same call in our staging environment: https://beta.blockdozer.com/api/addrs/:cashAddress/utxo/
(like Gerardo said in the other issue, a new release is in the works)

**Comment by alwaysAn0n** [comment]
@dario-ramos It's arguably worse.

```
	Checking https://beta.blockdozer.com/api/addrs/bitcoincash:qqhstfz5k4hm3h84harmkdasn2g22p6rts60d5knqn/utxo/
	status: 200

[ { address: '15HdX2MVg1GFxjLPEXZ9jBSgYuHZi1Q3Ma',
    txid: '710da9dfacfb6cf7a9bb0057022b4eac8c80d4ef02b824eb8781c1a2ad6cd9a2',
    vout: 1,
    scriptPubKey: '76a9142f05a454b56fb8dcf5bf47bb37b09a90a507435c88ac',
    amount: 0.00001717,
    satoshis: 1717,
    height: 533944,
    confirmations: 321 },
  { address: '15HdX2MVg1GFxjLPEXZ9jBSgYuHZi1Q3Ma',
    txid: '20d8d82aea7dc88af27990916a13b7565ff3ec21f3cb6e46efa97b4083e24670',
    vout: 2,
    amount: '0.00',
    satoshis: '26792',
    height: -1,
    confirmations: 0 } ]
```

The output in position zero was already there.  The output in position 1 was a few seconds old.  Both fields are returned as strings but now the `amount` is being shown as zero.  I sent ~ 25 cents USD

**Comment by alwaysAn0n** [comment]
@bitprim-phabricator @dario-ramos I often miss Github mentions so I made a gist containing the script I'm using to reproduce this.  It can be found at https://gist.github.com/alwaysAn0n/fa53ba0f71b61f288263bdd38d1fdcbd

I made a few slight modifications when removing it but it should work fine.

**Comment by alwaysAn0n** [comment]
Update:  Here are the results after a confirmation.

```
[ { address: '15HdX2MVg1GFxjLPEXZ9jBSgYuHZi1Q3Ma',
    txid: '20d8d82aea7dc88af27990916a13b7565ff3ec21f3cb6e46efa97b4083e24670',
    vout: 1,
    scriptPubKey: '76a9142f05a454b56fb8dcf5bf47bb37b09a90a507435c88ac',
    amount: 0.00026792,
    satoshis: 26792,
    height: 534265,
    confirmations: 3 },
  { address: '15HdX2MVg1GFxjLPEXZ9jBSgYuHZi1Q3Ma',
    txid: '710da9dfacfb6cf7a9bb0057022b4eac8c80d4ef02b824eb8781c1a2ad6cd9a2',
    vout: 1,
    scriptPubKey: '76a9142f05a454b56fb8dcf5bf47bb37b09a90a507435c88ac',
    amount: 0.00001717,
    satoshis: 1717,
    height: 533944,
    confirmations: 324 } ]
```

**Comment by renzobarrionuevo** [comment]
Hello alwaysAn0n 
We have made a new release of our API in which we have solved the problem that plated us.
 You can check it in https://blockdozer.com/api/addrs/:cashAddress/utxo/
Thank you very much for your cooperation.
